src/lib/facturacion_web/router.ex
defmodule FacturacionWeb.Router do
  use FacturacionWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {FacturacionWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FacturacionWeb do
    pipe_through :browser

    get "/", PageController, :index
    live "/clientes", ClienteLive.Index, :index
    live "/clientes/new", ClienteLive.Index, :new
    live "/clientes/:id/edit", ClienteLive.Index, :edit

    live "/clientes/:id", ClienteLive.Show, :show
    live "/clientes/:id/show/edit", ClienteLive.Show, :edit

    post "/export", ExportController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", FacturacionWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: FacturacionWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

src/lib/facturacion_web/live/cliente_live/form_component.ex
defmodule FacturacionWeb.ClienteLive.FormComponent do
  @moduledoc """
  Module for live form component to insert new clients
  """
  use FacturacionWeb, :live_component

  alias Facturacion.Clientes

  @impl true
  def update(%{cliente: cliente} = assigns, socket) do
    changeset = Clientes.change_cliente(cliente)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"cliente" => cliente_params}, socket) do
    changeset =
      socket.assigns.cliente
      |> Clientes.change_cliente(cliente_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"cliente" => cliente_params}, socket) do
    save_cliente(socket, socket.assigns.action, cliente_params)
  end

  defp save_cliente(socket, :edit, cliente_params) do
    case Clientes.update_cliente(socket.assigns.cliente, cliente_params) do
      {:ok, _cliente} ->
        {:noreply,
         socket
         |> put_flash(:info, "Cliente updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_cliente(socket, :new, cliente_params) do
    case Clientes.create_cliente(cliente_params) do
      {:ok, _cliente} ->
        {:noreply,
         socket
         |> put_flash(:info, "Cliente created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

src/lib/facturacion_web/live/cliente_live/index.ex
defmodule FacturacionWeb.ClienteLive.Index do
  @moduledoc """
  Module for display of list of clients
  """

  use FacturacionWeb, :live_view

  # import FacturacionWeb.Live.SharedComponents
  import FacturacionWeb.Live.DataTable

  alias Facturacion.Clientes
  alias Facturacion.Clientes.Cliente

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Cliente")
    |> assign(:cliente, Clientes.get_cliente!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Cliente")
    |> assign(:cliente, %Cliente{})
  end

  defp apply_action(socket, :index, params) do
    socket
    |> assign(:page_title, "Listing Clientes")
    |> assign(:params, params)
    |> assign(:clientes, list_clientes(params))
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    cliente = Clientes.get_cliente!(id)
    {:ok, _} = Clientes.delete_cliente(cliente)

    {:noreply, assign(socket, :clientes, list_clientes(%{}))}
  end

  defp list_clientes(params) do
    Clientes.list_clientes(params)
  end
end

src/lib/facturacion_web/live/cliente_live/show.ex
defmodule FacturacionWeb.ClienteLive.Show do
  @moduledoc """
  Module for display of a client
  """
  use FacturacionWeb, :live_view

  alias Facturacion.Clientes

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:cliente, Clientes.get_cliente!(id))}
  end

  defp page_title(:show), do: "Show Cliente"
  defp page_title(:edit), do: "Edit Cliente"
end

src/lib/facturacion_web/live/data_table.ex
defmodule FacturacionWeb.Live.DataTable do
  @moduledoc """
  Sort list of table
  """
  # import Phoenix.LiveView.Helpers
  alias Plug.Conn.Query

  @doc """
  Convert direction of sort from string to atom when value is asc, desc
  if no value is provide :asc is set
  """
  def sort(%{"sort_field" => field, "sort_direction" => direction})
      when direction in ~w(asc desc) do
    {String.to_atom(direction), String.to_existing_atom(field)}
  end

  def sort(_other) do
    {:asc, :id}
  end

  @doc """
  Helper function for setting correct live_patch in templates
  with the params for sort_direction and sort_field
  """
  def table_link(params, field) do
    direction = params["sort_direction"]

    opts =
      if params["sort_field"] == to_string(field) do
        [
          sort_field: field,
          sort_direction: reverse(direction)
        ]
      else
        [
          sort_field: field,
          sort_direction: "desc"
        ]
      end

    # live_patch(text, to: "?" <> querystring(params, opts), class: "link flex items-center")
    "?" <> querystring(params, opts)
  end

  def column_icon(params, field) do
    if params["sort_field"] == to_string(field) do
      if params["sort_direction"] == "asc" do
        "<Boxicons.up_arrow solid class='w-4 h-4 mr-1'/>"
      else
        "<Boxicons.down_arrow solid class='w-4 h-4 mr-1'/>"
      end
    else
      "<Boxicons.sort_alt class='w-4 h-4 mr-1'/>"
    end
  end

  def querystring(params, opts) do
    params = params |> Query.encode() |> URI.decode_query()

    opts = %{
      "page" => opts[:page],
      "sort_field" => opts[:sort_field] || params["sort_field"] || nil,
      "sort_direction" => opts[:sort_direction] || params["sort_direction"] || nil
    }

    params
    |> Map.merge(opts)
    |> Enum.filter(fn {_, v} -> v != nil end)
    |> Enum.into(%{})
    |> URI.encode_query()
  end

  defp reverse("desc"), do: "asc"
  defp reverse(_), do: "desc"
end

src/lib/facturacion_web/live/live_helpers.ex
defmodule FacturacionWeb.LiveHelpers do
  @moduledoc """
  Module for liveview helpers
  """
  # import Phoenix.LiveView
  # import Phoenix.LiveView.Helpers
  import Phoenix.Component

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.cliente_index_path(@socket, :index)}>
        <.live_component
          module={FacturacionWeb.ClienteLive.FormComponent}
          id={@cliente.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.cliente_index_path(@socket, :index)}
          cliente: @cliente
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <.link patch={@return_to} id="close" class="phx-modal-close" phx-click={hide_modal()}>✖</.link>
        <% else %>
          <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
end

src/lib/facturacion_web/live/pagination_component.ex
defmodule FacturacionWeb.Live.PaginationComponent do
  @moduledoc """
  Component for pagination of datatables.
  """
  use FacturacionWeb, :live_component
  import FacturacionWeb.Live.DataTable

  @distance 7

  @doc false
  def update(assigns, socket) do
    {
      :ok,
      socket
      |> assign(assigns)
      |> assign(pagination_assigns(assigns[:pagination_data]))
    }
  end

  @doc false
  def render(assigns) do
    ~H"""
    <div id={assigns[:id] || "pagination"} class="flex justify-center my-2">
      <%= if @total_pages > 1 do %>
        <div class="btn-group">
          <%= prev_link(@params, @page_number) %>
          <%= for num <- start_page(@page_number)..end_page(@page_number, @total_pages) do %>
            <%= live_patch num, to: "?#{querystring(@params, page: num)}", class: "ml-2 p-1.5 #{if @page_number == num, do: "ml-2 p-1.5 bg-blue-200 rounded-full bg-opacity-100 hover:text-white hover:bg-blue-500", else: "hover:font-bold"}" %>
          <% end %>
          <%= next_link(@params, @page_number, @total_pages) %>
        </div>
      <% end %>
    </div>
    """
  end

  defp pagination_assigns(%Scrivener.Page{} = pagination) do
    [
      page_number: pagination.page_number,
      page_size: pagination.page_size,
      total_entries: pagination.total_entries,
      total_pages: pagination.total_pages
    ]
  end

  def prev_link(conn, current_page) do
    if current_page != 1 do
      live_patch("Prev",
        to: "?" <> querystring(conn, page: current_page - 1),
        class: "btn btn-link"
      )
    else
      live_patch("Prev", to: "#", class: "btn btn-link btn-disabled")
    end
  end

  def next_link(conn, current_page, num_pages) do
    if current_page != num_pages do
      live_patch("Next",
        to: "?" <> querystring(conn, page: current_page + 1),
        class: "btn btn-link"
      )
    else
      live_patch("Next", to: "#", class: "btn btn-link btn-disabled")
    end
  end

  def start_page(current_page) when current_page - @distance <= 0, do: 1
  def start_page(current_page), do: current_page - @distance

  def end_page(current_page, 0), do: current_page

  def end_page(current_page, total)
      when current_page <= @distance and @distance * 2 <= total do
    @distance * 2
  end

  def end_page(current_page, total) when current_page + @distance >= total do
    total
  end

  def end_page(current_page, _total), do: current_page + @distance - 1
end

src/lib/facturacion_web/live/shared_components.ex
defmodule FacturacionWeb.Live.SharedComponents do
  @moduledoc """
  component to show dropdown when exporting data to excel, not in use yet
  """
  use Phoenix.Component
  alias Phoenix.LiveView.JS

  @doc false
  def dropdown(assigns) do
    # ~H"""
    # <div class="relative inline-block text-left">
    #   <button
    #     class="p-1.5 text-xs uppercase tracking-wider
    #           text-indigo-900 bg-indigo-200 rounded-lg bg-opacity-100 hover:font-bold"
    #     phx-click=
    #       { JS.toggle(to: "##{@id}",
    #          in: {"duration-300", "opacity-0", "opacity-100"},
    #         out: {"duration-75", "opacity-100", "opacity-0"})}
    #   >
    #     <%= render_slot(@toggle) %>
    #   </button>
    #   <div id={@id} class="absolute right-0 z-20 hidden"
    #     phx-click-away={JS.hide(to: "##{@id}", transition: {"duration-75", "opacity-100", "opacity-0"})}
    #   >
    #     <%= render_slot(@inner_block, assigns) %>
    #   </div>
    # </div>
    # """
    ~H"""
    <div class="relative inline-block text-left">
      <button class="btn btn-secondary" phx-click={ JS.toggle(to: "##{@id}", in: {"duration-300", "opacity-0", "opacity-100"}, out: {"duration-75", "opacity-100", "opacity-0"})  } >
        <%= render_slot(@toggle) %>
      </button>
      <div id={@id} class="absolute right-0 z-20 hidden" phx-click-away={JS.hide(to: "##{@id}", transition: {"duration-75", "opacity-100", "opacity-0"})}>
        <%= render_slot(@inner_block, assigns) %>
      </div>
    </div>
    """
  end
end

src/lib/facturacion_web/live/cliente_live/form_component.html.heex
<div class="mt-8 bg-indigo-400 px-3 py-3 rounded-lg shadow sm:mx-auto sm:w-full sm:max-w-md">
  <h2 class="text-center font-medium mb-3"><%= @title %></h2>

  <div class="bg-white py-8 px-6 shadow rounded-lg sm:px-10">
    <.form
      let={f}
      for={@changeset}
      id="cliente-form"
      phx-target={@myself}
      phx-change="validate"
      phx-submit="save"
      class="mb-0 space-y-6">

      <div>
        <%= label f, :name, class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1">
          <%= text_input f, :name, class: "w-full border border-gray-300 px-3 py-2 rounded-lg shadow-sm focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500" %>
        </div>
        <div class="mt-5 bg-red-200 px-2 rounded-lg font-light">
          <%= error_tag f, :name %>
        </div>
      </div>

      <div>
        <%= label f, :direccion, class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1">
          <%= text_input f, :direccion, class: "w-full border border-gray-300 px-3 py-2 rounded-lg shadow-sm focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500" %>
        </div>
        <div class="mt-5 bg-red-200 px-2 rounded-lg font-light">
          <%= error_tag f, :direccion %>
        </div>
      </div>
  
      <div>
        <%= label f, :cif, "CIF/NIF", class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1">
          <%= text_input f,
            :cif,
            class: "w-full border border-gray-300 px-3 py-2 rounded-lg shadow-sm focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500" %>
        </div>
        <div class="mt-5 bg-red-200 px-2 rounded-lg font-light">
          <%= error_tag f, :cif %>
        </div>
      </div>
    
      <div>
        <%=
          submit "Save",
          phx_disable_with: "Saving...",
          class: "w-full p-1.5 text-xs font-medium uppercase tracking-wider text-green-800 bg-blue-400 rounded-lg bg-opacity-50 hover:underline mx-1"
        %>
      </div>
    </.form>
  </div>
</div>

src/lib/facturacion_web/live/cliente_live/index.html.heex
<div class="mx-auto px-5 w-full pb-5">

  <h1 class="text-5xl font-bold mb-4 text-center">List Clientes</h1>

  <%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.cliente_index_path(@socket, :index)}>
    <.live_component
      module={FacturacionWeb.ClienteLive.FormComponent}
      id={@cliente.id || :new}
      title={@page_title}
      action={@live_action}
      cliente={@cliente}
      return_to={Routes.cliente_index_path(@socket, :index)}
    />
  </.modal>
  <% end %>
  <div class="overflow-auto rounded-lg shadow mb-4">
    <table class="w-full px-10 border-collapse table-auto">
      <thead class="bg-gray-200 border-b-2 border-gray-400">
        <tr>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            <.link patch={table_link(@params, :name)} class="link flex items-center">
              <%= if @params["sort_field"] == "name" do %>
                <%= case @params["sort_direction"] do %>
                <% "asc" -> %>
                  <Boxicons.up_arrow solid class="w-4 h-4 mr-1"/>
                <% "desc" -> %>
                  <Boxicons.down_arrow solid class="w-4 h-4 mr-1"/>
                <% end %>
              <% else %>
                <Boxicons.sort_alt class="w-4 h-4 mr-1"/>
              <% end %>
                Nombre
            </.link>
          </th>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            <.link patch={table_link(@params, :direccion)} class="link flex items-center">
              <%= if @params["sort_field"] == "direccion" do %>
                <%= case @params["sort_direction"] do %>
                <% "asc" -> %>
                  <Boxicons.up_arrow solid class="w-4 h-4 mr-1"/>
                <% "desc" -> %>
                  <Boxicons.down_arrow solid class="w-4 h-4 mr-1"/>
                <% end %>
              <% else %>
                <Boxicons.sort_alt class="w-4 h-4 mr-1"/>
              <% end %>
              Dirección
            </.link>
          </th>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            <.link patch={table_link(@params, :cif)} class="link flex items-center">
              <%= if @params["sort_field"] == "cif" do %>
                <%= case @params["sort_direction"] do %>
                <% "asc" -> %>
                  <Boxicons.up_arrow solid class="w-4 h-4 mr-1"/>
                <% "desc" -> %>
                  <Boxicons.down_arrow solid class="h-4 w-4" />
                <% end %>
              <% else %>
                <Boxicons.sort_alt class="w-4 h-4 mr-1"/>
              <% end %>
              CIF/NIF
            </.link>
          </th>
          <th class="p-3 text-sm font-semibold tracking-wide text-center">
            Acción
          </th>
        </tr>
      </thead>
      <tbody id="clientes" class="divide-y divide-gray-100">
        <%= for cliente <- @clientes do %>
          <tr id={"cliente-#{cliente.id}"} class="hover:bg-gray-300">
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap"><%= cliente.name %></td>
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap"><%= cliente.direccion %></td>
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap w-10"><%= cliente.cif %></td>
  
            <td class="whitespace-nowrap text-center w-20">
              <span
               class="p-1.5 text-xs font-medium uppercase tracking-wider text-blue-800 bg-blue-200 rounded-lg bg-opacity-50 hover:underline mx-1">
               <%= live_redirect "Show", to: Routes.cliente_show_path(@socket, :show, cliente) %>
              </span>
              <span
                class="p-1.5 text-xs font-medium uppercase tracking-wider text-green-800 bg-green-200 rounded-lg bg-opacity-50 hover:underline mx-1">
                <%= live_patch "Edit", to: Routes.cliente_index_path(@socket, :edit, cliente) %>
              </span>
              <span
                class="p-1.5 text-xs font-medium uppercase tracking-wider text-red-800 bg-red-200 rounded-lg bg-opacity-50 hover:underline mx-1">
                <%= link "Delete", to: "#", phx_click: "delete", phx_value_id: cliente.id, data: [confirm: "Are you sure?"] %>
              </span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= live_component FacturacionWeb.Live.PaginationComponent, params: @params, pagination_data: @clientes %>

  <span class="block w-fit my-2 p-1.5 text-xs uppercase tracking-wider text-green-900 bg-green-200 rounded-lg bg-opacity-100 hover:font-bold">
    <div class="flex">
      <Heroicons.user_plus class="w-4 h-4 mr-1"/>
      <%= live_patch "New Cliente", to: Routes.cliente_index_path(@socket, :new) %>
    </div>
  </span>

  <span class="block w-fit my-2 p-1.5 text-xs uppercase tracking-wider text-blue-900 bg-blue-200 rounded-lg bg-opacity-100 hover:font-bold">
    <div class="flex">
      <Heroicons.document_arrow_down class="w-4 h-4 mr-1"/>
      <%= link "Export csv", to: Routes.export_path(@socket, :create), method: :post, class: "px-1" %>
    </div>
  </span>
</div>

src/lib/facturacion_web/live/cliente_live/show.html.heex
<div class="mt-5">
  <h1 class="text-center font-medium mb-3">
    Show Cliente
  </h1>
</div>

<%= if @live_action in [:edit] do %>
  <.modal return_to={Routes.cliente_show_path(@socket, :show, @cliente)}>
    <.live_component
      module={FacturacionWeb.ClienteLive.FormComponent}
      id={@cliente.id}
      title={@page_title}
      action={@live_action}
      cliente={@cliente}
      return_to={Routes.cliente_show_path(@socket, :show, @cliente)}
    />
  </.modal>
<% end %>

<div class="max-w-md bg-white rounded-lg p-10 mx-10 shadow-md shadow-gray-600 w-auto">
  <ul class="list-outside hover:list-inside">
  
    <li class="mb-2">
      <strong class="mr-10">Name:</strong>
      <%= @cliente.name %>
    </li>
  
    <li class="mb-2">
      <strong class="mr-3">Direccion:</strong>
      <%= @cliente.direccion %>
    </li>
  
    <li class="mb-2">
      <strong class="mr-12">Cif: </strong>
      <%= @cliente.cif %>
    </li>
  
  </ul>
  <div class="mt-5 text-center">
    <span>
      <%= live_patch "Edit", to: Routes.cliente_show_path(@socket, :edit, @cliente),
        class: "p-1.5 text-sm font-semibold uppercase tracking-wider bg-gray-200 rounded-full text-gray-700 hover:underline mx-1"
      %>
    </span> |
    <span>
      <%= live_redirect "Back", to: Routes.cliente_index_path(@socket, :index),
        class: "p-1.5 text-sm font-semibold uppercase tracking-wider bg-gray-200 rounded-full text-gray-700 hover:underline mx-1"
      %>
    </span>
  </div>
</div>